version: 2
jobs:
  buildAZWebApp:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      # LOGIN ONTO AZURE WITH EXISTING SERVICE PRINCIPAL
      - run: |
          az login --service-principal -u $AZURE_SERVICE_PRINC --password $AZURE_SERVICE_PRINC_PASSWORD --tenant $AZURE_TENANT
          az -v
          az appservice plan create -g myResourceGroupVM -n ServicePlandt
          az webapp create -g myResourceGroupVM -p ServicePlandt -n dtapp2 --deployment-local-git
          
workflows:
  version: 2
  build_Infra:
    jobs:
      - buildAZWebApp
